---
- name: Installing software with homebrew
  homebrew: name={{ item }} state=present
  with_items: apps

- name: Checking for installed apps(casks)
  shell: brew cask list | grep {{ item }}
  register: installed_applications
  with_items: cask_apps
  ignore errors: true

- name: Installing apps with brew-cask
  shell: brew cask install {{ item }}
  with_items: applications
  when: item not in installed_applications.results|map(attribute='stdout')

- name: Adding postgres to LaunchAgents
  file:
    src: /usr/local/opt/postgresql/*.plist
    dest: ~/Library/LaunchAgents
    state: link

- name: Start postgres at startup
  shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

