---
- name: Installing software with apt
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-pip
    - python-dev
    - libpq-dev
    - libsnappy-dev
    - zsh
    - byobu
    - htop
    - default-jre
    - ruby
    - ruby-dev
    - rubygems
    - gcc
    - make

# TODO: Add install for golang
# TODO: Add task to add ~/.local/bin to PATH for pipsi
