---
- name: Install virtualenv
  pip: name={{ item }}
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Setting home directory for Mac
  set_fact:
    homedir: /Users/{{ devuser }}
  when: ansible_os_family == "Darwin"

- name: Setting home directory for Ubuntu
  set_fact:
    homedir: /home/{{ devuser }}
  when: ansible_distribution == "Ubuntu"

- name: Cloning oh-my-zsh repo
  become_user: "{{ devuser }}"
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ homedir }}/.oh-my-zsh

- name: Creating new .zshrc
  become_user: "{{ devuser }}"
  copy:
    src={{ homedir }}/.oh-my-zsh/templates/zshrc.zsh-template
    dest={{ homedir }}/.zshrc
    backup=yes

- name: Setting zsh as default shell
  user: name={{ devuser }} shell=/bin/zsh

# - name: Checking for .vim directory
  # stat: path=/home/{{ devuser }}/.vim/autoload
  # register: vimfound

# - name: Making .vim directory if it doesn't exist
  # become_user: "{{ devuser }}"
  # shell: mkdir -p ~/.vim/autoload

- name: Making .vim/autoload directory if it doesn't exist
  become_user: "{{ devuser }}"
  files: path=~/.vim/autoload state=directory

- name: Making .vim/tmp directory if it doesn't exist
  become_user: "{{ devuser }}"
  files: path=~/.vim/tmp state=directory

- name: Making .vim/backup directory if it doesn't exist
  become_user: "{{ devuser }}"
  files: path=~/.vim/backup state=directory

- name: Adding vim-plug package manager
  become_user: "{{ devuser }}"
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ homedir }}/.vim/autoload/plug.vim
    backup=yes

- name: Adding vim solarized repo
  become_user: "{{ devuser }}"
  git:
    repo=https://github.com/altercation/vim-colors-solarized.git
    dest={{ homedir }}/.vim/plugged

- name: Cloning dotfiles
  git:
    repo=https://github.com/MikeDelaney/dotfiles.git
    dest={{ homedir }}/dotfiles

- name: Checking for existing .bashrc
  stat: path={{ homedir }}/.bashrc
  register: found

- name: Backing up .bashrc if it exists
  command: mv {{ homedir }}/.bashrc {{ homedir }}/.bashrc.orig
  when: found.stat.exists and ansible_distribution == "Ubuntu"

- name: Symlink dotfiles
  become_user: "{{ devuser }}"
  file: path={{ homedir }}/{{ item }} src={{ homedir }}/dotfiles/{{ item }} state=link
  with_items:
    - .bashrc
    - .vimrc
    - .bash

- name: Symlink nested dotfiles
  become_user: "{{ devuser }}"
  file: path={{ homedir }}/{{ item.name }} src={{ homedir }}/dotfiles/{{ item.dirname }}/{{ item.name }} state=link
  with_items:
    - { dirname: 'git', name: '.gitconfig' }
    - { dirname: 'git', name: '.gitignore_global' }
    - { dirname: 'git', name: '.git-completion.sh' }
    - { dirname: 'git', name: '.git-prompt.sh' }

- name: Install fpm packaging tool
  become_user: "{{ devuser}}"
  gem:
      name: fpm
      state: present

- name: Create dirs for Go
  become_user: "{{ devuser }}"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homedir }}/Go"
    - "{{ homedir }}/Go/src/gitub.com/MikeDelaney"

- name: Download pipsi
  get_url: https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py

- name: Install pipsi
  shell: python /tmp/get-pipsi.py
